# Generated by Django 4.2.16 on 2024-10-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_mechanicprofile_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='web_site',
            field=models.TextField(blank=True),
        ),
    ]
